apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: sonar-pvc
    namespace: devops
  nfs:
    server: 192.168.137.3
    path: "/volume1/Sonarqube"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: devops
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: "sonar-pv"