apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: sonar-pvc
    namespace: devops
  iscsi:
    chapAuthSession: false
    chapAuthDiscovery: false
    targetPortal: 192.168.137.3:3260
    iqn: 'iqn.2000-01.com.synology:drive.sonar.402fcc5ed94'
    lun: 01
    fsType: 'ext4'
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: devops
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: "sonar-pv"