- name: Install Sonarqube
  hosts: localhost
  vars_files:
    - files/sonarqube_vars.yaml
  vars:
    namespace: devops

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift
      delegate_to: localhost

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Create monitoring namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
      delegate_to: localhost

    - name: Add Oteemo Search Repo
      community.kubernetes.helm_repository:
        name: oteemocharts
        repo_url: "https://oteemo.github.io/charts"
      delegate_to: localhost

#    - name: Add sonarqube database
#      community.general.postgresql_db:
#        login_host: 192.168.137.72
#        login_password: '{{ postgrespassword }}'
#        name: sonardb
#
#
#    - name: Add sonarqube database user
#      community.general.postgresql_user:
#        login_host: 192.168.137.72
#        login_password: '{{ postgrespassword }}'
#        db: sonardb
#        name: sonaruser
#        password: '{{ sonarqubepostgrespassword }}'
#        priv: ALL
#

    - name: Copy Customization
      copy:
        src: ../sonarqube-values.yaml
        dest: /tmp/

    - name: Apply Sonarqube
      command: >
        helm install -n "{{ namespace }}" sonarqube oteemocharts/sonarqube
        -f /tmp/sonarqube-values.yaml
        --set postgresql.postgresqlPassword="{{ sonarqubepostgrespassword }}"
      delegate_to: localhost