# You would run this on the Kubernetes Raspberry Pi Control Plane
# Important: Run this first!

- name: Reset Sonarqube
  hosts: localhost
  vars:
    namespace: devops

  tasks:
    - name: Reset Sonarqube
      command: helm uninstall -n "{{ namespace }}" sonarqube
